### ISSUE TITLE
Move equipment DB to Service reader

### ISSUE THREAD

**Issue by richardtown** [richardtown/ServiceSheetManager#23]
Equipment table
- Id
- Barcode
- Description
- SerialNumber
- CaliibrationPeriodDays
- EquipmentKitId

Equipment Kit
- Id
- Barcode
- Description

Location Table
- Id
- EquipmentId
- UserScanned
- UserFirstName
- UserSurname
- SubmissionNumber
- LocationCode
- DtReported - Sort by these
- Notes

CalibrationRecord
- Id
- EquipmentId
- CertNumber
- Passed
- DtCalibrated - Sort by these

**Comment by RichardTownMTT** [comment]
Tables created and change scripts generated
